/// Flutter icons Iconmed
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconmed
///      fonts:
///       - asset: fonts/Iconmed.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Iconmed {
  Iconmed._();

  static const _kFontFam = 'Iconmed';
  static const _kFontPkg = null;

  static const IconData allergy1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disease = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surgery = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaccine = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
